name: Django CI

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests and collect coverage
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
  build:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.repository_owner }}
          password: "${{ secrets.CR_PAT }}"
          registry: ghcr.io
          image_name: ${{ github.event.repository.name }}

      - name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: "${{ secrets.CR_PAT }}"
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          dry-run: false
          older-than: 7
          keep-last: 2

  deploy:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    needs: [test, build]
    env:
      CAPROVER_URL: "${{ secrets.CAP_URL }}"
      CAPROVER_PASSWORD: "${{ secrets.CAP_PASS }}"

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install caprover
        run: npm install -g caprover

      - name: Deploy images
        run: |
          caprover deploy --imageName $IMAGE --caproverApp todo
          caprover deploy --imageName $IMAGE --caproverApp todo-beat
          caprover deploy --imageName $IMAGE --caproverApp todo-worker
        env:
          IMAGE: https://ghcr.io/${{ github.repository }}:latest
