name: Django CI

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests and collect coverage
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build image and push GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/sainak/task-manager:latest
          # ghcr.io/${{ github.repository }}:latest
          push: ${{ github.ref == 'refs/heads/deploy' }}

  deploy:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    needs: [test, build]
    env:
      CAPROVER_URL: "${{ secrets.CAP_URL }}"
      CAPROVER_PASSWORD: "${{ secrets.CAP_PASS }}"

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install caprover
        run: npm install -g caprover

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Deploy images
        run: |
          caprover deploy --imageName $IMAGE --caproverApp todo
          caprover deploy --imageName $IMAGE --caproverApp todo-beat
          caprover deploy --imageName $IMAGE --caproverApp todo-worker
        env:
          IMAGE: ghcr.io/sainak/task-manager:latest
